# These are supported funding model platforms

 custom: ['https://docs.qq.com/doc/DYWJKZ2ZtdmVPZmVY?tdsourcetag=s_pcqq_send_grpfile&ADUIN=750215287&ADSESSION=1643950660&ADTAG=CLIENT.QQ.5845_.0&ADPUBNO=27178']
